"""Structure contract tests for HEPHAESTUS (anchor file).

These checks are part of the immutable contract: they must stay green
before and after every phase. They enforce the config schema, the build
declarations (CMake + Makefile), the canonical tensor names contracted
in src/model/model_def.h, and the absence of prohibited attribution
markers in the tree.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]

MAKEFILE_TARGETS = [
    "setup", "export", "configure", "build", "test", "golden", "quantize",
    "bench", "bench-all", "chat", "lint", "docker-build", "clean",
]

PATHS_KEYS = ["model_manifest", "tensors_table", "weights", "tokenizer_dir",
              "checkpoint"]
GOLDEN_KEYS = ["prompts_file", "fixtures_dir", "tokens_per_prompt",
               "max_abs_diff", "cosine_min"]
KV_KEYS = ["page_tokens", "quant"]
BENCH_KEYS = ["prompts", "warmup", "max_new_tokens", "modes"]

CANONICAL_TENSORS = [
    "embedding.weight",
    "layer.{i}.attn_norm.weight",
    "layer.{i}.attn.wq.weight",
    "layer.{i}.attn.wk.weight",
    "layer.{i}.attn.wv.weight",
    "layer.{i}.attn.wo.weight",
    "layer.{i}.ffn_norm.weight",
    "layer.{i}.ffn.w_gate.weight",
    "layer.{i}.ffn.w_up.weight",
    "layer.{i}.ffn.w_down.weight",
    "final_norm.weight",
    "lm_head.weight",
]

FORBIDDEN_MARKERS = [
    "as an ai",
    "i am an ai",
    "i'm an ai",
    "language model trained",
    "i cannot",
    "i can't",
    "i'm sorry",
    "generated by",
    "generated with",
    "co-authored-by",
    "chatgpt",
    "openai",
    "anthropic",
    "claude",
    "gpt-4",
    "copilot",
]

_SCAN_DIRS = ["src", "tests", "scripts", "docs"]


def _iter_scan_targets():
    for d in _SCAN_DIRS:
        root = REPO_ROOT / d
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if path.is_file() and path.suffix in {
                ".py", ".cpp", ".h", ".md", ".txt", ".yaml", ".yml", ".json",
            }:
                yield path


@pytest.fixture(scope="session")
def config() -> dict:
    return yaml.safe_load(
        (REPO_ROOT / "config.yaml").read_text(encoding="utf-8")
    )


# --- config contract ------------------------------------------------------


def test_paths_keys(config: dict) -> None:
    for key in PATHS_KEYS:
        assert key in config["paths"], f"paths missing key: {key}"


def test_golden_tolerances(config: dict) -> None:
    golden = config["golden"]
    for key in GOLDEN_KEYS:
        assert key in golden, f"golden missing key: {key}"
    assert golden["max_abs_diff"] == pytest.approx(1.0e-2)
    assert golden["cosine_min"] == pytest.approx(0.999)
    assert golden["tokens_per_prompt"] > 0


def test_arch_defaults(config: dict) -> None:
    arch = config["arch_defaults"]
    assert arch["rms_norm_eps"] == pytest.approx(1.0e-5)
    assert arch["rope_theta"] == pytest.approx(10000.0)
    assert arch["d_head"] is None  # computed as d_model / n_head


def test_quant_invariants(config: dict) -> None:
    quant = config["quant"]
    assert quant["int4_group"] in (32, 64, 128)
    assert quant["ternary_scale"] in ("mean_abs", "absmax")
    assert quant["int8_axis"] in ("out_channel", "in_channel")


@pytest.mark.parametrize("key", KV_KEYS)
def test_kv_keys(config: dict, key: str) -> None:
    assert key in config["kv"]


def test_kv_page_tokens_power_of_two(config: dict) -> None:
    page = config["kv"]["page_tokens"]
    assert page >= 8 and (page & (page - 1)) == 0


@pytest.mark.parametrize("key", BENCH_KEYS)
def test_bench_keys(config: dict, key: str) -> None:
    assert key in config["bench"]


def test_bench_modes(config: dict) -> None:
    modes = config["bench"]["modes"]
    assert set(modes) == {"fp32", "int8", "int4", "ternary"}


# --- build contract -------------------------------------------------------


def test_cmake_declares_project_and_std17() -> None:
    text = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    assert re.search(r"project\s*\(\s*hephaestus\b", text)
    assert re.search(r"CXX_STANDARD\s+17", text)
    assert re.search(r"enable_testing\s*\(", text)


def test_cmake_has_no_third_party_link() -> None:
    """The engine has ZERO third-party libraries: no BLAS, no Eigen, no
    nlohmann. find_package / pkg_check_modules are prohibited."""
    text = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    assert not re.search(r"find_package\s*\(", text), \
        "third-party dependency detected in CMakeLists.txt"
    assert "Eigen" not in text and "BLAS" not in text and "OpenBLAS" not in text


def test_makefile_targets_declared() -> None:
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    declared = set(re.findall(r"^([a-zA-Z_-]+)\s*:", text, flags=re.MULTILINE))
    missing = [t for t in MAKEFILE_TARGETS if t not in declared]
    assert not missing, f"Makefile missing targets: {missing}"


def test_model_def_covers_canonical_names() -> None:
    text = (REPO_ROOT / "src/model/model_def.h").read_text(encoding="utf-8")
    for i in range(6):  # nano has 6 layers
        for template in CANONICAL_TENSORS:
            name = template.format(i=i)
            assert name in text, f"model_def.h missing canonical name: {name}"


def test_model_def_arch_contract() -> None:
    text = (REPO_ROOT / "src/model/model_def.h").read_text(encoding="utf-8")
    for constant in ("384", "6", "1024", "8000"):
        assert constant in text, f"model_def.h missing arch constant {constant}"


# --- attribution markers ---------------------------------------------------


def test_no_ai_markers() -> None:
    offenders = []
    for path in _iter_scan_targets():
        text = path.read_text(encoding="utf-8", errors="replace").lower()
        for marker in FORBIDDEN_MARKERS:
            if marker in text:
                rel = path.relative_to(REPO_ROOT)
                offenders.append(f"{rel}: contains '{marker}'")
    assert not offenders, (
        "prohibited attribution markers found:\n" + "\n".join(offenders)
    )
